### ISSUE TITLE
Issue with ool

### ISSUE THREAD

**Issue by lovehitler** [SarahH12099/Windows-Repo-Tool#1]
When trying to download liberty lite dev which is a free tweak it’ keeps telling me it’s a paid tweak and can’t be downloaded here’s a video sample a

https://user-images.githubusercontent.com/79390142/108615062-3683da00-73ce-11eb-9ea1-50f61dabff5a.MOV

**Comment by SarahH12099** [comment]
From your video you are using a malicious piracy repo that on purposely blocks certain connections. Please only use official developers repos. This will be closed due to the malicious repo.
