### ISSUE TITLE
repo is not opened

### ISSUE THREAD

**Issue by hakankocyigit** [SarahH12099/Windows-Repo-Tool#2]
I added a few repos but when I try to open a repo, I get the error mentioned below. Am I doing something wrong?

"An unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and try to continue. If you click Exit, the application will be closed immediately."

**Comment by SarahH12099** [comment]
Are you connected to the internet and is the repo url right? That error usually means that you either aren’t connected to the internet or the repo url isn’t supported or right.

**Comment by hakankocyigit** [comment]
> Are you connected to the internet and is the repo url right? That error usually means that you either aren’t connected to the internet or the repo url isn’t supported or right.

internet connected. I add the correct url without deleting the https I use in cydia, but when I try to open it, it gets an error

**Comment by SarahH12099** [comment]
What is the repo url please?

**Comment by hakan5816** [comment]
![Uploading image.jpg…]()

**Comment by hakankocyigit** [comment]
> What is the repo url please?

https://https://apt.fouadraheb.com/
https://https://repo.packix.com/
https://http://apt.thebigboss.org/repofiles/cydia/
https://https://repo.chariz.com/
I tried these

**Comment by SarahH12099** [comment]
You didn’t enter the repo urls right, you entered https:// twice in the repo url.

**Comment by hakankocyigit** [comment]
> You didn’t enter the repo urls right, you entered https:// twice in the repo url.

oh sorry it was getting https when i copy and paste thanks :)
