### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by lovehitler** [SarahH12099/Windows-Repo-Tool#3]
Keeps saying I can’t download tweak cause it’s a paid tweak even though it’s not since liberty lite is free here’s video 

https://user-images.githubusercontent.com/79390142/108627026-67412f00-7421-11eb-918e-9a806d0d037b.MOV

**Comment by SarahH12099** [comment]
You have already been answered. Closing again. https://github.com/SarahH12099/Windows-Repo-Tool/issues/1#issuecomment-782801604
