### ISSUE TITLE
Downloaded debs naming scheme

### ISSUE THREAD

**Issue by sevenpastzeero** [SarahH12099/Windows-Repo-Tool#4]
Is it possible to name the downloaded debs as their original names "com.devname.tweakname_version.deb"

**Comment by SarahH12099** [comment]
Debs are downloaded based off the names from the repos currently, I will look into adding this in future updates.

**Comment by SarahH12099** [comment]
No reason to close this, keeping this open until its added

**Comment by SarahH12099** [comment]
This has been added in v2.0.0, v2.0.0 will be going live hopefully today.

**Comment by SarahH12099** [comment]
v2.0.0 is now live: https://github.com/SarahH12099/Windows-Repo-Tool/releases

**Comment by sevenpastzeero** [comment]
Thank you.
