### ISSUE TITLE
[Feature Request] Download Multiple Packages at Once

### ISSUE THREAD

**Issue by Fahrenheit** [SarahH12099/Windows-Repo-Tool#7]
The ability to download multiple packages would be an awesome feature. I am working on an archival project for r/LegacyJailbreak and having the ability to download everything from an older repo would be a massive help.

Thank you!

**Comment by SarahH12099** [comment]
Sorry, that isn't possible, the project would require a queue system like cydia/sileo still where you have to press each package one at a time and an entire download at once system would break the entire project.
